### ISSUE TITLE
enumeration value 'UIInterfaceOrientationUnknown' not handled in switch

### ISSUE THREAD

**Issue by bobsapps** [ebaker355/DPToastView#3]
Pods/DPToastView/DPToastView.m:247:13: warning: enumeration value 'UIInterfaceOrientationUnknown' not handled in switch [-Wswitch]
    switch (orientation) {

Just need to add one of these to suppress the warning...

        case UIInterfaceOrientationUnknown:
            break;
        default:
            break;

Xcode 6.0.1

**Comment by ebaker355** [comment]
Updated! Thanks!
